version: '3.7'

services:
    ks-frontend-demo:
        image: "${DOCKER_REGISTRY}/ks-frontend-demo:${TAG}"
        build:
            context: .
            dockerfile: ./apps/Dockerfile
            args:
                APP: ks-frontend-demo
                DOCKER_REGISTRY: ${DOCKER_REGISTRY}   
                TAG: ${TAG}          

    backend:
        image: "${DOCKER_REGISTRY}/ks-backend-demo:${TAG}"
        build:
            context: ./backend/
            dockerfile: ./Dockerfile