apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: os-demo01
  creationTimestamp: "2021-06-28T11:40:41Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: postgres
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-weight: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: Go-http-client
    operation: Update
    time: "2021-06-28T11:40:41Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:volume.kubernetes.io/selected-node: {}
    manager: k3s
    operation: Update
    time: "2021-06-28T11:40:41Z"
  name: postgres-pv-claim
  namespace: demo-keystone
  resourceVersion: "55499"
  uid: 374a5811-2f64-4ba8-aa1c-6ebff8a0b7a3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Pending
