

repository: opensaasreg.azurecr.io
clusterIssuer: dns-solver
backendUrl: https://core-test.opensaas.com.au/api/graphql
stripeKey: pk_test_TEST_KEY
imagePullSecret: opensaasregsecret
nameOverride: ""
fullnameOverride: ""

backend:
    name: backend
    replicaCount: 1
    hostname: core-test.opensaas.com.au
    containerPort: 3000
    env:
        FRONTEND: https://ks-frontend-demo.opensaas.com.au
        DATABASE_URL: postgres://somename:1234@postgres/dbname
        SESSION_SECRET: SOME_SECURE_STRING
        STRIPE_SECRET: sk_test_1234
        AUTH0_DOMAIN: opensaas.au.auth0.com
        AUTH0_CLIENT_ID: Auth0ClientID
        AUTH0_CLIENT_SECRET: Auth0ClientSecret
    image:
        name: opensaas-backend
        pullPolicy: Always
        # Overrides the image tag whose default is the chart appVersion.
        tag: ""
apps:
    - name: next-app
      hostname: next-app.opensaas.com.au
      replicaCount: 1
      image:
        name: next-app
        pullPolicy: Always
        tag: ""

localDatabase:
  create: false
  dbname: demo-keystone
  dbadmin: postgres
  dbpass: securepassword

serviceAccount:
  # Specifies whether a service account should be created
  create: true