

repository: opensaas
clusterIssuer: dns-solver
backendUrl: https://ks-backend-demo.opensaas.com.au/api/graphql
stripeKey: pk_test_TEST_KEY
imagePullSecret: opensaasregsecret
nameOverride: ""
fullnameOverride: ""

backend:
    name: backend
    replicaCount: 1
    hostname: ks-backend-demo.opensaas.org.au
    containerPort: 3000
    env:
        FRONTEND: https://ks-frontend-demo.opensaas.org.au
        DATABASE_URL: postgres://somename:1234@postgres/dbname
        SESSION_SECRET: SOME_SECURE_STRING
        STRIPE_SECRET: sk_test_1234
        AUTH0_DOMAIN: opensaas.au.auth0.com
        AUTH0_CLIENT_ID: Auth0ClientID
        AUTH0_CLIENT_SECRET: Auth0ClientSecret
    image:
        name: ks-backend-demo
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: ""
apps:
    - name: ks-frontend-demo
      hostname: ks-frontend-demo.opensaas.org.au
      replicaCount: 1
      image:
        name: ks-frontend-demo
        pullPolicy: IfNotPresent
        tag: ""

localDatabase:
  create: true
  dbname: demo-keystone
  dbadmin: postgres
  dbpass: securepassword

serviceAccount:
  # Specifies whether a service account should be created
  create: true